# Generated by Django 5.2.15 on 2026-07-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('chain_external_id', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=9)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('adjusts_parent_calories', models.BooleanField(default=False)),
                ('adjusts_parent_price', models.BooleanField(default=False)),
                ('base_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_removal', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('store_name', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=32)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('zip_code', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(blank=True, max_length=8)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('chain_external_id', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('mandatory', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='menu.option')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='option',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.optiongroup'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('chain_external_id', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=9)),
                ('base_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('max_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('calories_separator', models.CharField(blank=True, max_length=8)),
                ('is_disabled', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='menu.product'),
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('description', 'Description'), ('removal_option', 'Removal Option'), ('both', 'Both')], max_length=16)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='menu.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='menu.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='products', through='menu.ProductIngredient', to='menu.ingredient'),
        ),
        migrations.CreateModel(
            name='HoursPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handoff_type', models.CharField(max_length=32)),
                ('day', models.CharField(max_length=16)),
                ('end_day', models.CharField(blank=True, max_length=16)),
                ('opens', models.CharField(max_length=8)),
                ('closes', models.CharField(max_length=8)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='menu.restaurant')),
            ],
            options={
                'ordering': ['handoff_type', 'id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.restaurant'),
        ),
        migrations.AddConstraint(
            model_name='optiongroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent_option__isnull', True), ('product__isnull', False)), models.Q(('parent_option__isnull', False), ('product__isnull', True)), _connector='OR'), name='optiongroup_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_product_ingredient'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['base_calories'], name='menu_produc_base_ca_d392f7_idx'),
        ),
    ]
