# Generated by Django 5.2.15 on 2026-07-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_single_use',
            field=models.BooleanField(default=False),
        ),
    ]
